// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOPSxxHPG-NytzCEX-99ZLuy_4aLTGGJs',
    appId: '1:58378210121:web:3e41bf35e97b4a90856898',
    messagingSenderId: '58378210121',
    projectId: 'liked-app-1b792',
    authDomain: 'liked-app-1b792.firebaseapp.com',
    storageBucket: 'liked-app-1b792.appspot.com',
    measurementId: 'G-CT23R460Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3mEPPHkIUNd7GNOeOHLtvuQpzaRbFOcg',
    appId: '1:58378210121:android:d5120ae53e1b9718856898',
    messagingSenderId: '58378210121',
    projectId: 'liked-app-1b792',
    storageBucket: 'liked-app-1b792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTK24gJrVQ6-UzixbDVLzoykqihzVdUhs',
    appId: '1:58378210121:ios:b128f48dfe84f919856898',
    messagingSenderId: '58378210121',
    projectId: 'liked-app-1b792',
    storageBucket: 'liked-app-1b792.appspot.com',
    iosBundleId: 'com.example.precticalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTK24gJrVQ6-UzixbDVLzoykqihzVdUhs',
    appId: '1:58378210121:ios:b128f48dfe84f919856898',
    messagingSenderId: '58378210121',
    projectId: 'liked-app-1b792',
    storageBucket: 'liked-app-1b792.appspot.com',
    iosBundleId: 'com.example.precticalApp',
  );
}
